[metadata]
name = "Harter-Heightway Dragon"

[l-system]
dimensions = "2D"
axiom = "FX"
iterations = 16

[l-system.rules]
X = "X+YF+"
Y = "-FX-Y"

[turtle]
angle = 90.0

[colors]
background = [0.0, 0.0, 0.0]

[colors.line]
mode = "hue_cycle"
initial = [0.9, 0.0, 0.0]
