[metadata]
name = "Gosper Curve"

[l-system]
dimensions = "2D"
axiom = "XF"
iterations = 4
angle = 60.0

[l-system.rules]
X = "X+YF++YF-FX--FXFX-YF+"
Y = "-FX+YFYF++YF+FX--FX-Y"

[colors.line.hue_cycle]
