[metadata]
name = "Hilbert Curve"

[l-system]
dimensions = "2D"
axiom = "A"
iterations = 5

[l-system.rules]
A = "-BF+AFA+FB-"
B = "+AF-BFB-FA+"

[turtle]
angle = 90.0

[colors]
background = "#000000"

[colors.line]
mode = "hue_cycle"
initial = "#e60000"
