[metadata]
name = "Koch Snowflake"

[l-system]
dimensions = "2D"
axiom = "F++F++F"
iterations = 6

[l-system.rules]
F = "F-F++F-F"

[turtle]
angle = 60.0

[colors]
background = "#000000"

[colors.line]
mode = "hue_cycle"
initial = "#e60000"
