[metadata]
name = "Peano Curve"

[l-system]
dimensions = "2D"
axiom = "L"
iterations = 4
angle = 90.0

[l-system.rules]
L = "LFRFL-F-RFLFR+F+LFRFL"
R = "RFLFR+F+LFRFL-F-RFLFR"

[colors.line.hue_cycle]
