[metadata]
name = "3D Plant"

[l-system]
dimensions = 3
axiom = "X"
iterations = 6

[l-system.rules]
X = "F[+X][-X][&X][^X]"
F = "FF"

[turtle]
angle = 30.0
step = 1.0
initial_heading = 90.0

[colors]
background = [0.0, 0.0, 0.0]

[colors.line]
mode = "gradient"
start = [0.35, 0.35, 0.05]
end = [0.2, 0.85, 0.25]
