[metadata]
name = "3D Plant"

[l-system]
dimensions = "3D"
axiom = "X"
iterations = 6

[l-system.rules]
X = "F[+X][-X][&X][^X]"
F = "FF"

[turtle]
angle = 30.0
initial_heading = 90.0

[colors]
background = "#000000"

[colors.line.gradient]
start = "#59590d"
end = "#33d940"
