[metadata]
name = "Plant A"

[l-system]
dimensions = "2D"
axiom = "X"
iterations = 7
angle = 25.0
initial_heading = 90.0

[l-system.rules]
X = "F+[[X]-X]-F[-FX]+X"
F = "FF"

[colors.line.gradient]
start = "#0d590d"
end = "#99e61a"
