[metadata]
name = "Plant A"

[l-system]
dimensions = "2D"
axiom = "X"
iterations = 7

[l-system.rules]
X = "F+[[X]-X]-F[-FX]+X"
F = "FF"

[turtle]
angle = 25.0
initial_heading = 90.0

[colors]
background = "#000000"

[colors.line]
mode = "gradient"
start = "#0d590d"
end = "#99e61a"
