name = "3D Plant"
dimensions = 3
axiom = "X"
iterations = 6
angle = 30
initial_heading = 90.0

[line_color]
mode = "gradient"
start = [0.35, 0.35, 0.05]
end = [0.2, 0.85, 0.25]

[rules]
X = "F[+X][-X][&X][^X]"
F = "FF"
