[metadata]
name = "Plant A"

[l-system]
dimensions = "2D"
axiom = "X"
iterations = 7

[l-system.rules]
X = "F+[[X]-X]-F[-FX]+X"
F = "FF"

[turtle]
angle = 25.0
initial_heading = 90.0

[colors]
background = [0.0, 0.0, 0.0]

[colors.line]
mode = "gradient"
start = [0.05, 0.35, 0.05]
end = [0.6, 0.9, 0.1]
