[metadata]
name = "Sierpinski Triangle"

[l-system]
dimensions = "2D"
axiom = "FXF-FF-FF"
iterations = 9

[l-system.rules]
F = "FF"
X = "-FXF+FXF+FXF-"

[turtle]
angle = 120.0

[colors]
background = "#000000"

[colors.line.hue_cycle]
initial = "#e60000"
