[metadata]
name = "Sierpinski Triangle"

[l-system]
dimensions = 2
axiom = "FXF-FF-FF"
iterations = 9

[l-system.rules]
F = "FF"
X = "-FXF+FXF+FXF-"

[turtle]
angle = 120.0
step = 1.0
initial_heading = 0.0

[colors]
background = [0.0, 0.0, 0.0]

[colors.line]
mode = "hue_cycle"
initial = [0.9, 0.0, 0.0]
