[metadata]
name = "Snowflake"

[l-system]
dimensions = "2D"
axiom = "[F]+[F]+[F]+[F]+[F]+[F]"
iterations = 4
angle = 60.0

[l-system.rules]
F = "F[+FF][-FF]FF[+F][-F]FF"

[colors.line.gradient]
start = "#e699ff"
end = "#1a80ff"
topological_depth = true
