[metadata]
name = "3D Ternary Tree"

[l-system]
dimensions = "3D"
axiom = "FA"
iterations = 8

[l-system.rules]
A = '[&FA]///[&FA]///[&FA]'
F = 'FF'

[turtle]
angle = 40.0
initial_heading = 90.0

[colors.line.gradient]
start = "#8c400d"
end = "#1af273"
