[metadata]
name = "3D Tree"

[l-system]
dimensions = "3D"
axiom = "A"
iterations = 7

[l-system.rules]
A = 'F[+/A]/[-/A]F[&/A]/[^/A]'
F = 'FF'

[turtle]
angle = 40.0
initial_heading = 90.0

[colors]
background = [0.0, 0.0, 0.0]

[colors.line]
mode = "hue_cycle"
initial = [0.9, 0.0, 0.0]
