[metadata]
name = "3D Tree"

[l-system]
dimensions = "3D"
axiom = "A"
iterations = 7
angle = 40.0
initial_heading = 90.0

[l-system.rules]
A = 'F[+/A]/[-/A]F[&/A]/[^/A]'
F = 'FF'

[colors.line.hue_cycle]
