[metadata]
name = "3D Tree"

[l-system]
dimensions = "3D"
axiom = "A"
iterations = 7

[l-system.rules]
A = 'F[+/A]/[-/A]F[&/A]/[^/A]'
F = 'FF'

[turtle]
angle = 40.0
initial_heading = 90.0

[colors]
background = "#000000"

[colors.line.hue_cycle]
initial = "#e60000"
