[package]
name = "lsystem-renderer"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
png = ["dep:futures-channel", "dep:png", "dep:gloo-timers"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { workspace = true, features = ["futures"], optional = true }

[dependencies]
lsystem-core.workspace = true
bytemuck = { version = "1", features = ["derive"] }
encase = "0.12"
futures-channel = { version = "0.3", optional = true }
glam = { workspace = true, features = ["encase", "bytemuck"] }
log.workspace = true
png = { version = "0.18", optional = true }
wgpu.workspace = true

[build-dependencies]
wgsl_to_wgpu = "0.18"

[dev-dependencies]
pollster = "0.4"
