[package]
name = "lsystem-web-app"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lsystem-core = { workspace = true, features = ["svg"] }
lsystem-app-model = { workspace = true }
lsystem-renderer = { workspace = true, features = ["png"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
js-sys.workspace = true
leptos = { version = "0.8", features = ["csr"] }
log.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "BlobPropertyBag",
    "Document",
    "DomRect",
    "Element",
    "Event",
    "EventTarget",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlElement",
    "KeyboardEvent",
    "MouseEvent",
    "PointerEvent",
    "Url",
    "WheelEvent",
    "Window",
] }
wgpu.workspace = true
