[package]
name = "lsystem-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
svg = []

[dependencies]
glam = { workspace = true, features = ["bytemuck"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml_edit = { version = "0.25.11", features = ["serde"] }
