[package]
name = "lsystem-app"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lsystem-core = { path = "../lsystem-core", features = ["svg"] }
lsystem-renderer = { path = "../lsystem-renderer" }
egui = "0.34"
egui-wgpu = "0.34"
egui-winit = { version = "0.34", default-features = false, features = ["wayland", "x11", "links"] }
include_dir = "0.7"
log = "0.4"
wgpu = "29"
winit = "0.30"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
pollster = "0.4"
rfd = "0.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Blob",
    "BlobPropertyBag",
    "CssStyleDeclaration",
    "Document",
    "Element",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlElement",
    "Url",
    "Window",
] }
