[package]
name = "lsystem-app"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam.workspace = true
lsystem-core = { workspace = true, features = ["svg"] }
lsystem-app-model = { workspace = true }
lsystem-renderer = { workspace = true, features = ["png"] }
log.workspace = true
web-time.workspace = true
wgpu.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced = { workspace = true, features = ["advanced", "wgpu", "web-colors", "crisp", "thread-pool", "linux-theme-detection", "x11", "wayland"] }
env_logger = "0.11"
rfd = "0.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced = { workspace = true, features = ["advanced", "wgpu", "webgl", "web-colors", "fira-sans", "crisp"] }
console_error_panic_hook.workspace = true
console_log.workspace = true
gloo-file.workspace = true
gloo-timers = { workspace = true, features = ["futures"] }
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "CssStyleDeclaration",
    "Document",
    "Element",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlElement",
    "Window",
] }
